In [ ]:
import numpy as np
# a = np.tile(np.arange(1, 7), (3, 2))
# print(a)
# print(a.T)
# print(a.size)
# print(a.ravel())
# print(a.T.ravel())
# b = a.ravel()
# print(b)
# # b = b.reshape((2, 3))
# print(b)
# c=np.zeros((3,2))
# d=c.T.reshape(3*2)
# d[0]=50
# print(c)
# print(d)
z=np.arange(4*3*2)
# print(z)
z = np.arange(4*3*2).reshape(4, 3, 2)
# print(z)
# print(z.shape)
# print(z[0,2,1])

z=np.arange(4)
z.resize((8,))
# print(z)    
# print(z.resize((4,)))

o = np.array([4, 3, 1, 2])
q = np.argsort(o)
# print(q)
a = np.array([[1, 4, 2], [3, 1, 0]])
b = np.sort(a, axis=1)
print(b)
print(a.shape)
print(b.shape)
a.reshape(3,2)
print(a)
b.tolist()
print(b)




[[1 2 4]
 [0 1 3]]
(2, 3)
(2, 3)
[[1 4 2]
 [3 1 0]]
