In [13]:
import numpy as np
a = np.tile(np.arange(1, 7), (3, 2))
# print(a)
# print(a.T)
# print(a.size)
# print(a.ravel())
# print(a.T.ravel())
# b = a.ravel()
# print(b)
# # b = b.reshape((2, 3))
# print(b)
# c=np.zeros((3,2))
# d=c.T.reshape(3*2)
# d[0]=50
# print(c)
# print(d)
z=np.arange(4*3*2)
print(z)
z = np.arange(4*3*2).reshape(4, 3, 2)
print(z)
print(z.shape)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]
(4, 3, 2)
