In [4]:
import numpy as np
a = np.tile(np.arange(1, 7), (3, 2))
print(a)
print(a.T)
print(a.size)
print(a.ravel())
print(a.T.ravel())
b = a.ravel()
print(b)
# b = b.reshape((2, 3))
print(b)




[[1 2 3 4 5 6 1 2 3 4 5 6]
 [1 2 3 4 5 6 1 2 3 4 5 6]
 [1 2 3 4 5 6 1 2 3 4 5 6]]
[[1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]
 [5 5 5]
 [6 6 6]
 [1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]
 [5 5 5]
 [6 6 6]]
36
[1 2 3 4 5 6 1 2 3 4 5 6 1 2 3 4 5 6 1 2 3 4 5 6 1 2 3 4 5 6 1 2 3 4 5 6]
[1 1 1 2 2 2 3 3 3 4 4 4 5 5 5 6 6 6 1 1 1 2 2 2 3 3 3 4 4 4 5 5 5 6 6 6]
[1 2 3 4 5 6 1 2 3 4 5 6 1 2 3 4 5 6 1 2 3 4 5 6 1 2 3 4 5 6 1 2 3 4 5 6]
[1 2 3 4 5 6 1 2 3 4 5 6 1 2 3 4 5 6 1 2 3 4 5 6 1 2 3 4 5 6 1 2 3 4 5 6]
